### ISSUE TITLE
Applicants should be able to see their dashboard and take first two tasks upon login

### ISSUE THREAD

**Issue by prank7** [AltCampus/orbit#15]
Backend API + Frontend component + Integration.

- Applicants should be able to see the HTML/CSS task and attempt it in a CodeSandBox and then submit the Codesandbox URL in our app.
- After the first task is complete they should be able to see the Codewars task and then submit the Codewars profile URL in our app.

Deadline - 28th November 2019, 8 pm

**Comment by PrateekxCodes** [comment]
we are done with this task in #23 branch
